name: Free RDP with Cloudflare

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Set strong password & Enable RDP
      run: |
        net user runneradmin "RdpTest@123"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Get-NetFirewallRule -DisplayName "Remote Desktop - User Mode (TCP-In)" | Set-NetFirewallRule -Enabled True

    - name: Download cloudflared
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile "cloudflared.exe"

    - name: Start Cloudflare Tunnel
      run: |
        Start-Process -WindowStyle hidden -FilePath ".\cloudflared.exe" -ArgumentList "tunnel", "--url", "tcp://localhost:3389"
        Start-Sleep -Seconds 10

    - name: Keep job alive
      run: |
        for ($i = 0; $i -lt 360; $i++) {
          Write-Output "Alive minute $i"
          Start-Sleep -Seconds 60
        }
